services:
  - type: web
    name: tiktok-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    healthCheckPath: /health
